In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
bridge_data_path = "D:\\Bridge_Data\\CSV\\Cleaned_Full_Data_V6.csv"
df_bridge = pd.read_csv(bridge_data_path, dtype=str,usecols=['STRUCTURE_NUMBER_008','LAT_016','LONG_017'])

In [5]:
df_bridge

       STRUCTURE_NUMBER_008             LONG_017             LAT_016
0                    56_NEI  -108.69419444444445   44.84097222222223
1                    56_NEH  -104.32308333333333   42.15830555555556
2                    56_NDY  -109.61693333333332  43.525219444444446
3                    56_NDU  -109.26782222222222   44.40872777777778
4                    56_NDP  -105.10608055555555   42.95828055555556
...                     ...                  ...                 ...
612749   01_000001331700710              -87.625                34.8
612750   01_000001014002450   -87.38166666666666              34.805
612751   01_000000883039900               -87.97   34.45166666666667
612752   01_00000000000S703   -87.56913888888889  31.105611111111113
612753   01_00000000000S702   -87.57041111111111   31.10303888888889

[612754 rows x 3 columns]

In [3]:
pred_data_path = "D:\\Bridge_Data\\CSV\\Bridge_Predictions.csv"
df_preds = pd.read_csv(pred_data_path)

In [6]:
df_preds['STRUCTURE_NUMBER_008'] = df_preds.apply(lambda x: x['STRUCTURE_NUMBER_008'].rstrip(),axis=1)

In [9]:
df_preds

,STRUCTURE_NUMBER_008,Estimate Volatility Outlook,NN 2023 Bridge Condition,NN 2024 Bridge Condition,NN 2022 Bridge Condition,NN 2021 Bridge Condition,NN 2020 Bridge Condition,NN 2019 Bridge Condition,NN 2018 Bridge Condition,NN 2017 Bridge Condition,...,RF 2003 Bridge Condition,RF 2002 Bridge Condition,RF 2001 Bridge Condition,RF 2000 Bridge Condition,RF 1999 Bridge Condition,RF 1998 Bridge Condition,RF 1997 Bridge Condition,RF 1996 Bridge Condition,RF 1995 Bridge Condition,RF 1994 Bridge Condition
0,12_CEPSAJFL-ORTONA,Stable,3,3,3,3,3,3,3,3,...,3,3,3,3,3,2,3,0,0,0
1,12_AFFLXLWU18169,Stable,1,1,1,2,2,3,3,3,...,0,0,0,0,0,0,0,0,0,0
2,12_AFFLNVZR00002,Stable,3,3,3,3,3,3,3,3,...,0,0,0,0,0,0,0,0,0,0
3,12_AFFLNVZR00001,Stable,3,3,3,2,3,3,3,3,...,0,0,0,0,0,0,0,0,0,0
4,12_AFFLKYJM00003,Stable,3,3,3,3,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613040,06_ 1CA0141,Stable,3,3,3,2,2,3,3,3,...,3,0,0,0,0,0,0,0,0,0
613041,06_ 1CA0095,Stable,3,3,3,2,2,3,3,3,...,0,0,0,0,0,0,0,0,0,0
613042,06_ 1CA0070,Stable,3,3,3,2,2,2,2,2,...,3,0,0,0,0,0,0,0,0,0
613043,06_ 19P0005,Stable,1,1,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
613044,06_ 06 0021,Stable,3,3,3,2,2,2,2,2,...,0,0,0,0,0,0,0,0,0,0

In [7]:
df_merged_preds = pd.merge(df_bridge, df_preds, left_on='STRUCTURE_NUMBER_008',right_on='STRUCTURE_NUMBER_008',how='left')

In [8]:
df_merged_preds

,STRUCTURE_NUMBER_008,LONG_017,LAT_016,Estimate Volatility Outlook,NN 2023 Bridge Condition,NN 2024 Bridge Condition,NN 2022 Bridge Condition,NN 2021 Bridge Condition,NN 2020 Bridge Condition,NN 2019 Bridge Condition,...,RF 2003 Bridge Condition,RF 2002 Bridge Condition,RF 2001 Bridge Condition,RF 2000 Bridge Condition,RF 1999 Bridge Condition,RF 1998 Bridge Condition,RF 1997 Bridge Condition,RF 1996 Bridge Condition,RF 1995 Bridge Condition,RF 1994 Bridge Condition
0,56_NEI,-108.69419444444445,44.84097222222223,Stable,3.0,3.0,3.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,56_NEH,-104.32308333333333,42.15830555555556,Stable,3.0,3.0,3.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,56_NDY,-109.61693333333332,43.525219444444446,Stable,3.0,2.0,3.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,56_NDU,-109.26782222222222,44.40872777777778,Stable,3.0,3.0,3.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,56_NDP,-105.10608055555555,42.95828055555556,Stable,3.0,3.0,3.0,2.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612749,01_000001331700710,-87.625,34.8,Stable,3.0,3.0,3.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0
612750,01_000001014002450,-87.38166666666666,34.805,Stable,3.0,3.0,3.0,2.0,2.0,1.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0
612751,01_000000883039900,-87.97,34.45166666666667,Stable,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,0.0,0.0,0.0
612752,01_00000000000S703,-87.56913888888889,31.105611111111113,Stable,3.0,3.0,3.0,3.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
612753,01_00000000000S702,-87.57041111111111,31.10303888888889,Stable,3.0,3.0,3.0,3.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
df_merged_preds.to_csv('MODEL_PREDICTIONS_V2.csv', index=False)